-- TODO: TRIGGER DE AUTOINCREMENT PARA LA LLAVE
CREATE TABLE SEG_PERMISO(
    SEG_PERMISO		INT 			NOT NULL,
    DESCRIPCION_ESP	VARCHAR2(256)	NOT NULL,
    DESCRIPCION_ING	VARCHAR2(256)	NOT NULL,
    
    CONSTRAINT	'SEG_PERMISO_PK' 		PRIMARY KEY (SEG_PERMISO),
	CONSTRAINT	'DESCRIPCION_ESP_REGEX'	CHECK(REGEXP_LIKE(DESCRIPCION_ESP, '[a-zA-ZñÑáéíóúÁÉÍÓÚ]|\s*'),
	CONSTRAINT	'DESCRIPCION_ING_REGEX'	CHECK(REGEXP_LIKE(DESCRIPCION_ESP, '[a-zA-Z]|\s*')
);

-- TODO: TRIGGER QUE DEPENDIENTE DEL SEG_ROL LE PONGA NOMBRE_ROL
CREATE TABLE SEG_ROL(
    SEG_ROL		INT												NOT NULL,
	NOMBRE_ROL	ENUM('SuperUser', 'Administrator', 'Student') 	NOT NULL,
	
    CONSTRAINT 'SEG_ROL_PK' PRIMARY KEY (SEG_ROL),
	CONSTRAINT 'SEG_ROL_RANGE' CHECK (NUMERO_ROL BETWEEN 1 and 3),
	CONSTRAINT 'NOMBRE_ROL_ENUM' CHECK(NOMBRE_ROL IN ('SuperUser','Administrator','Student'))
);
