INSERT INTO SEG_PERMISO
VALUES (1, 'Ver información de programa', 'View program information');

INSERT INTO SEG_PERMISO
VALUES (1, 'Editar información de programa', 'Edit program information');

INSERT INTO SEG_PERMISO
VALUES (1, 'Ver cursos del programa', 'View program courses');

INSERT INTO SEG_PERMISO
VALUES (1, 'Borrar programa', 'Delete program');

INSERT INTO SEG_PERMISO
VALUES (1, 'Agregar programa', 'Add program');

INSERT INTO SEG_PERMISO
VALUES (1, 'Agrega pregunta', 'Add question');

INSERT INTO SEG_PERMISO
VALUES (1, 'Ver pregunta', 'View question');

INSERT INTO SEG_PERMISO
VALUES (1, 'Editar pregunta', 'Edit question');

INSERT INTO SEG_PERMISO
VALUES (1, 'Borrar pregunta', 'Delete question');

INSERT INTO SEG_PERMISO
VALUES (1, 'Editar permisos', 'Edit permissions');

INSERT INTO SEG_PERMISO
VALUES (1, 'Agregar formulario', 'Add form');

INSERT INTO SEG_PERMISO
VALUES (1, 'Ver formulario', 'View form');

INSERT INTO SEG_PERMISO
VALUES (1, 'Borrar formulario', 'Delete form');

INSERT INTO SEG_PERMISO
VALUES (1, 'Ver tablero estudiante', 'View student Dashboard');

INSERT INTO SEG_PERMISO
VALUES (1, 'Ver tablero administrador', 'View administrator dashboard');

INSERT INTO SEG_PERMISO
VALUES (1, 'Crear solicitud', 'Create application');

INSERT INTO SEG_PERMISO
VALUES (1, 'Editar solicitud', 'Edit application');

INSERT INTO SEG_PERMISO
VALUES (1, 'Ver solicitud', 'View application');

INSERT INTO SEG_PERMISO
VALUES (1, 'Agregar usuario', 'Add user');

INSERT INTO SEG_PERMISO
VALUES (1, 'Editar información de otro usuario', 'Edit other user information');

INSERT INTO SEG_PERMISO
VALUES (1, 'Ver información de otro usuario', 'View other user information');

INSERT INTO SEG_PERMISO
VALUES (1, 'Borrar otro usuario', 'Delete other user');

INSERT INTO SEG_PERMISO
VALUES (1, 'Ver curso', 'View course');

INSERT INTO SEG_PERMISO
VALUES (1, 'Editar curso', 'Edit course');

INSERT INTO SEG_PERMISO
VALUES (1, 'Borrar curso', 'Delete course');

INSERT INTO SEG_PERMISO
VALUES (1, 'Agregar curso', 'Add course');

INSERT INTO SEG_PERMISO
VALUES (1, 'Editar formulario', 'Edit form');

INSERT INTO SEG_PERMISO
VALUES (1, 'Indice pregunta', 'Question index');

INSERT INTO SEG_PERMISO
VALUES (1, 'Descargar solicitud en PDF', 'Download application in PDF');

INSERT INTO SEG_PERMISO
VALUES (1, 'Indice usuario', 'User index');

INSERT INTO SEG_PERMISO
VALUES (1, 'Indice formulario', 'Form index');

INSERT INTO SEG_POSEE
VALUES(1,0);

INSERT INTO SEG_POSEE
VALUES(2,0);

INSERT INTO SEG_POSEE
VALUES(3,0);

INSERT INTO SEG_POSEE
VALUES(1,1);

INSERT INTO SEG_POSEE
VALUES(1,2);

INSERT INTO SEG_POSEE
VALUES(2,2);

INSERT INTO SEG_POSEE
VALUES(3,2);

INSERT INTO SEG_POSEE
VALUES(1,3);

INSERT INTO SEG_POSEE
VALUES(1,4);

INSERT INTO SEG_POSEE
VALUES(1,5);

INSERT INTO SEG_POSEE
VALUES(2,5);

INSERT INTO SEG_POSEE
VALUES(1,6);

INSERT INTO SEG_POSEE
VALUES(2,6);

INSERT INTO SEG_POSEE
VALUES(1,7);

INSERT INTO SEG_POSEE
VALUES(2,7);

INSERT INTO SEG_POSEE
VALUES(1,8);

INSERT INTO SEG_POSEE
VALUES(2,8);

INSERT INTO SEG_POSEE
VALUES(1,9);

INSERT INTO SEG_POSEE
VALUES(1,10);

INSERT INTO SEG_POSEE
VALUES(2,10);

INSERT INTO SEG_POSEE
VALUES(1,11);

INSERT INTO SEG_POSEE
VALUES(2,11);

INSERT INTO SEG_POSEE
VALUES(1,12);

INSERT INTO SEG_POSEE
VALUES(2,12);

INSERT INTO SEG_POSEE
VALUES(3,13);

INSERT INTO SEG_POSEE
VALUES(1,14);

INSERT INTO SEG_POSEE
VALUES(2,14);

INSERT INTO SEG_POSEE
VALUES(3,15);

INSERT INTO SEG_POSEE
VALUES(3,16);

INSERT INTO SEG_POSEE
VALUES(1,17);

INSERT INTO SEG_POSEE
VALUES(2,17);

INSERT INTO SEG_POSEE
VALUES(3,17);

INSERT INTO SEG_POSEE
VALUES(1,18);

INSERT INTO SEG_POSEE
VALUES(2,18);

INSERT INTO SEG_POSEE
VALUES(1,19);

INSERT INTO SEG_POSEE
VALUES(1,20);

INSERT INTO SEG_POSEE
VALUES(2,20);

INSERT INTO SEG_POSEE
VALUES(1,21);

INSERT INTO SEG_POSEE
VALUES(1,22);

INSERT INTO SEG_POSEE
VALUES(2,22);

INSERT INTO SEG_POSEE
VALUES(3,22);

INSERT INTO SEG_POSEE
VALUES(1,23);

INSERT INTO SEG_POSEE
VALUES(2,23);

INSERT INTO SEG_POSEE
VALUES(1,24);

INSERT INTO SEG_POSEE
VALUES(2,24);

INSERT INTO SEG_POSEE
VALUES(1,25);

INSERT INTO SEG_POSEE
VALUES(2,25);

INSERT INTO SEG_POSEE
VALUES(1,26);

INSERT INTO SEG_POSEE
VALUES(2,26);

INSERT INTO SEG_POSEE
VALUES(1,27);

INSERT INTO SEG_POSEE
VALUES(2,27);

INSERT INTO SEG_POSEE
VALUES(1,28);

INSERT INTO SEG_POSEE
VALUES(2,28);

INSERT INTO SEG_POSEE
VALUES(1,29);

INSERT INTO SEG_POSEE
VALUES(2,29);

INSERT INTO SEG_POSEE
VALUES(1,30);

INSERT INTO SEG_POSEE
VALUES(2,30);

COMMIT;